CREATE DATABASE madereira;

USE madereira;

CREATE TABLE produto(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
quantidade INT,
valor FLOAT
);


CREATE TABLE usuario(
id INT AUTO_INCREMENT PRIMARY KEY,
usuario VARCHAR(100),
senha VARCHAR(8)
);